version: "3.9"
services:
  php:
    image: "mmhk/php-docker:8-fpm"
    volumes:
      - .:/var/www/html
      - ../.:/var/www
    environment:
      WWW_UID: 1000
      WWW_GID: 1000
  nginx:
    depends_on:
       - php
    image: "mmhk/php-docker:nginx-ws-fpm"
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ../.:/var/www
    links:
     - "php"
    environment:
      WS_PROXY_HOST: "http://php:5342"
      FPM_HOST: "php:9000"